### PR TITLE
Sorry missed an issue.

### PR DESCRIPTION
**Pull request by niraj-rayalla**

### CODE REVIEW

**Comment by SrJohnathan** [comment]
tomorrow I'm going to debug win, linux and android, if everything is working, I'll send it to maven central, launch new version 2.2.2

**Comment by niraj-rayalla** [comment]
Hi. Just wanted to ask if the new version will be released anytime soon so that I can reference the dependencies from Maven Central. If not, that's fine.

**Comment by SrJohnathan** [comment]
I didn't have time, but I'll send it today, as soon as possible

Em qui, 28 de abr de 2022 18:09, niraj-rayalla ***@***.***>
escreveu:

**Comment by niraj-rayalla** [comment]
Awesome. thanks!

**Comment by SrJohnathan** [comment]
Version 2.2.2  👍

Em qui, 28 de abr de 2022 18:30, niraj-rayalla ***@***.***>
escreveu:

**Pull request merged**
